import type { Metadata } from 'next';
import { inter } from '@/app/fonts';
import '@/app/globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} font-inter bg-neutral-200 antialiased dark:bg-neutral-900`}
      >
        {children}
      </body>
    </html>
  );
}
